# Site identity
title: Stephanie Kestelman
description: Stephanie Kestelman's website
email: stephaniekestelman@gmail.com
bio: Harvard Economics PhD Student

url: "https://skestelman.github.io"

twitter_username: stephkestelman
github_username: skestelman

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  footnote_nr: 1
  math_engine: mathjax

# Blog post URLs
permalink: /blog/:year/:month/:day/:title/

# Plugins supported by GitHub Pages
plugins:
  - jekyll-sitemap

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
