theme: jekyll-theme-minimal
title: Stephanie Kestelman
Description: This website is currently under construction. Come back in the near future. In the meantime, please look for me on LinkedIn.
bio: Research Assistant at Princeton University, previously at the University of Chicago Booth School of Business. Swarthmore College '16.
