# Site settings
theme: jekyll-theme-minimal
title: Stephanie Kestelman
email: stephaniekestelman@gmail.com
Description: Stephanie Kestelman's website.
bio: Incoming Harvard Economics PhD Student, previously a Research Assistant at Princeton University the University of Chicago Booth School of Business. Swarthmore College '16.
url: "http:///skestelman.github.io" # the base hostname & protocol for this site
twitter_username: stephkestelman
github_username:  skestelman
permalink: /blog/:year/:month/:title.html
gems:
    - jekyll-sitemap

# Build settings
markdown: kramdown
